name = "IndirectShooting"
uuid = "552ddee8-f2c8-412c-9a93-d98e9622e980"
authors = ["Grant Hecht"]
version = "0.1.0"

[deps]
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"

[compat]
NLsolve = "4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
